server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/orders/**

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
